{{- if and .Values.persistence.enabled (not .Values.persistence.saves.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "valheim-server.fullname" . }}-saves
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.saves.accessMode }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.saves.size }}
{{- end }}

{{- if and .Values.persistence.enabled (not .Values.persistence.server.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "valheim-server.fullname" . }}-server
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.server.accessMode }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.server.size }}
{{- end }}

{{- if and .Values.persistence.enabled (not .Values.persistence.backups.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "valheim-server.fullname" . }}-backups
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.backups.accessMode }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
{{- end }}