apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim-server.fullname" . }}
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
type: Opaque
data:
  server-password: {{ .Values.server.password | b64enc | quote }}