apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim-server.fullname" . }}
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.server.port }}
      targetPort: game
      protocol: UDP
      name: game
    - port: {{ add .Values.server.port 1 }}
      targetPort: game-1
      protocol: UDP
      name: game-1
    - port: {{ add .Values.server.port 2 }}
      targetPort: game-2
      protocol: UDP
      name: game-2
  selector:
    {{- include "valheim-server.selectorLabels" . | nindent 4 }}