apiVersion: v2
name: zomboid-server
description: A Helm chart for deploying a Project Zomboid dedicated server on Kubernetes
type: application
version: 0.1.1
appVersion: "41.78.19"
home: https://projectzomboid.com
icon: https://cdn2.steamgriddb.com/icon/57b7e11eca1be1c2f09e9e9c4cfb9b28/32/256x256.png
maintainers:
  - name: janip81
    email: jani@techmonkeys.se
keywords:
  - game
  - zomboid
  - project-zomboid
  - gameserver
  - dedicated-server
sources:
  - https://github.com/Danixu/project-zomboid-server-docker
  - https://github.com/fpsacha/zomboid-control-panel
  - https://github.com/janip81/helm-charts/tree/main/charts/zomboid-server
deprecated: false
annotations:
  artifacthub.io/links: |
    - name: Server image source
      url: https://github.com/Danixu/project-zomboid-server-docker
    - name: Panel image source
      url: https://github.com/fpsacha/zomboid-control-panel
  artifacthub.io/images: |
    - name: zomboid-server
      image: danixu86/project-zomboid-dedicated-server:41.78.19-release
    - name: zomboid-panel
      image: ghcr.io/fpsacha/zomboid-panel:v1.0.66
