apiVersion: v2
name: zomboid-server
description: A Helm chart for deploying a Project Zomboid dedicated server on Kubernetes
type: application
version: 0.1.21
appVersion: "42.20.2"
home: https://projectzomboid.com
icon: https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg
maintainers:
  - name: janip81
    email: jani@techmonkeys.se
keywords:
  - game
  - zomboid
  - project-zomboid
  - gameserver
  - dedicated-server
sources:
  - https://github.com/Danixu/project-zomboid-server-docker
  - https://github.com/fpsacha/zomboid-control-panel
  - https://github.com/janip81/helm-charts/tree/main/charts/zomboid-server
deprecated: false
annotations:
  artifacthub.io/links: |
    - name: Server image source
      url: https://github.com/Danixu/project-zomboid-server-docker
    - name: Panel image source
      url: https://github.com/fpsacha/zomboid-control-panel
  artifacthub.io/images: |
    - name: zomboid-server
      image: danixu86/project-zomboid-dedicated-server:42.20.2-release
    - name: zomboid-panel
      image: ghcr.io/fpsacha/zomboid-panel:v1.1.34
