apiVersion: v2
name: k8s-ui
description: A Helm chart for deploying a multi-cluster Kubernetes dashboard with CAPI integration.
type: application
version: 1.0.0
appVersion: "0.1.0"
home: https://github.com/janip81/k8s-ui
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
maintainers:
  - name: janip81
    email: jani@techmonkeys.se
keywords:
  - kubernetes
  - dashboard
  - capi
  - multi-cluster
  - ui
sources:
  - https://github.com/janip81/k8s-ui
  - https://github.com/kubernetes-sigs/cluster-api
  - https://github.com/kubernetes/dashboard
deprecated: false
annotations:
  artifacthub.io/links: |
    - name: Project Source
      url: https://github.com/janip81/k8s-ui
    - name: Cluster API
      url: https://github.com/kubernetes-sigs/cluster-api
  artifacthub.io/images: |
    - name: frontend
      image: ghcr.io/janip81/k8s-ui-frontend:latest
    - name: backend
      image: ghcr.io/janip81/k8s-ui-backend:latest
