apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "holidayhub.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "holidayhub.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if .Values.s3.endpoint }}
  S3_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  S3_BUCKET:   {{ .Values.s3.bucket | quote }}
  S3_REGION:   {{ .Values.s3.region | default "garage" | quote }}
  {{- end }}
