{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "holidayhub.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "holidayhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.secretEnv.NEXTAUTH_SECRET | quote }}
  {{- if not .Values.cnpg.enabled }}
  DATABASE_URL: {{ .Values.secretEnv.DATABASE_URL | default "" | quote }}
  {{- end }}
  {{- if .Values.secretEnv.S3_ACCESS_KEY }}
  S3_ACCESS_KEY: {{ .Values.secretEnv.S3_ACCESS_KEY | quote }}
  S3_SECRET_KEY: {{ .Values.secretEnv.S3_SECRET_KEY | quote }}
  {{- end }}
  {{- if .Values.secretEnv.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_ID: {{ .Values.secretEnv.SPOTIFY_CLIENT_ID | quote }}
  SPOTIFY_CLIENT_SECRET: {{ .Values.secretEnv.SPOTIFY_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if .Values.secretEnv.METRICS_BEARER_TOKEN }}
  METRICS_BEARER_TOKEN: {{ .Values.secretEnv.METRICS_BEARER_TOKEN | quote }}
  {{- end }}
{{- end }}
