{{- if .Values.gatewayApi.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "n8n.fullname" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  hostnames:
    - {{ .Values.gatewayApi.host | quote }}
  parentRefs:
  {{- range .Values.gatewayApi.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
  {{- end }}
  {{- if .Values.gatewayApi.tls.enabled }}
  tls:
    mode: Terminate
    certificateRefs:
      - kind: Secret
        name: {{ .Values.gatewayApi.tls.secretName }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "n8n.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
