{{- if .Values.secrets.create -}}
{{- $ns := .Release.Namespace -}}

{{- /* Encryption secret */ -}}
{{- $enc := .Values.secrets.encryption -}}
{{- $existingEnc := lookup "v1" "Secret" $ns $enc.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $enc.name }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with $enc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- if .Values.secrets.useStringData }}
stringData:
  {{ $enc.key }}: {{- if $enc.value | default "" | trim | ne "" -}}
    {{ $enc.value | quote }}
  {{- else if and $existingEnc (index $existingEnc.data $enc.key) -}}
    {{ (index $existingEnc.data $enc.key) | b64dec | quote }}
  {{- else -}}
    {{ randAlphaNum 64 | quote }}
  {{- end }}
{{- else }}
data:
  {{ $enc.key }}: {{- if $enc.value | default "" | trim | ne "" -}}
    {{ $enc.value | b64enc }}
  {{- else if and $existingEnc (index $existingEnc.data $enc.key) -}}
    {{ index $existingEnc.data $enc.key }}
  {{- else -}}
    {{ randAlphaNum 64 | b64enc }}
  {{- end }}
{{- end }}

{{- /* Database secret */ -}}
{{- $db := .Values.secrets.database -}}
{{- $existingDb := lookup "v1" "Secret" $ns $db.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $db.name }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  {{- with $db.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- if .Values.secrets.useStringData }}
stringData:
  {{ $db.key }}: {{- if $db.value | default "" | trim | ne "" -}}
    {{ $db.value | quote }}
  {{- else if and $existingDb (index $existingDb.data $db.key) -}}
    {{ (index $existingDb.data $db.key) | b64dec | quote }}
  {{- else -}}
    {{ randAlphaNum 24 | quote }}
  {{- end }}
  {{- with $db.userKey }}
  {{ . }}: {{- if $db.userValue | default "" | trim | ne "" -}}
    {{ $db.userValue | quote }}
  {{- else if and $existingDb (index $existingDb.data $db.userKey) -}}
    {{ (index $existingDb.data $db.userKey) | b64dec | quote }}
  {{- else -}}
    n8n
  {{- end }}
  {{- end }}
{{- else }}
data:
  {{ $db.key }}: {{- if $db.value | default "" | trim | ne "" -}}
    {{ $db.value | b64enc }}
  {{- else if and $existingDb (index $existingDb.data $db.key) -}}
    {{ index $existingDb.data $db.key }}
  {{- else -}}
    {{ randAlphaNum 24 | b64enc }}
  {{- end }}
  {{- with $db.userKey }}
  {{ . }}: {{- if $db.userValue | default "" | trim | ne "" -}}
    {{ $db.userValue | b64enc }}
  {{- else if and $existingDb (index $existingDb.data $db.userKey) -}}
    {{ index $existingDb.data $db.userKey }}
  {{- else -}}
    {{ "n8n" | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
