apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  {{- if .Values.persistence.enabled }}
  strategy:
    type: Recreate
  {{- end }}
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: {{ .Values.service.port }}
            - name: websocket
              containerPort: {{ .Values.service.websocketPort }}
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config
            - name: data
              mountPath: /mosquitto/data
      volumes:
        - name: config
          {{- if .Values.auth.enabled }}
          projected:
            sources:
              - configMap:
                  name: mosquitto-config
              - secret:
                  name: {{ .Values.auth.existingSecret | default "mqtt-auth" }}
          {{- else }}
          configMap:
            name: mosquitto-config
          {{- end }}
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
