{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: mqtt-auth
  labels:
    app.kubernetes.io/name: {{ include "mqtt-broker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  passwd: {{ printf "%s:%s" .Values.auth.username .Values.auth.password | b64enc }}
{{- end }}