{{- if not .Values.zomboid.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zomboid-server.fullname" . }}
  labels:
    {{- include "zomboid-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.zomboid.secretKeys.adminPassword }}: {{ .Values.zomboid.adminPassword | toString | b64enc | quote }}
  {{ .Values.zomboid.secretKeys.rconPassword }}: {{ .Values.zomboid.rconPassword | toString | b64enc | quote }}
  {{ .Values.zomboid.secretKeys.serverPassword }}: {{ .Values.zomboid.serverPassword | toString | b64enc | quote }}
{{- end }}
