apiVersion: v1
kind: Service
metadata:
  name: {{ include "zomboid-server.fullname" . }}-game
  labels:
    {{- include "zomboid-server.labels" . | nindent 4 }}
  {{- with .Values.service.game.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.game.type }}
  {{- if and (eq .Values.service.game.type "LoadBalancer") .Values.service.game.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.game.loadBalancerIP }}
  {{- end }}
  {{- if eq .Values.service.game.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.game.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: game
      port: {{ .Values.service.game.ports.game }}
      targetPort: game
      protocol: UDP
    - name: direct
      port: {{ .Values.service.game.ports.direct }}
      targetPort: direct
      protocol: UDP
    {{- if .Values.service.game.steamPorts.enabled }}
    - name: steam1
      port: {{ .Values.service.game.steamPorts.port1 }}
      targetPort: steam1
      protocol: UDP
    - name: steam2
      port: {{ .Values.service.game.steamPorts.port2 }}
      targetPort: steam2
      protocol: UDP
    {{- end }}
  selector:
    {{- include "zomboid-server.selectorLabels" . | nindent 4 }}
