{{- if .Values.mqtt.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pci-usb-watchdog.fullname" . }}-mqtt
  labels:
    {{- include "pci-usb-watchdog.labels" . | nindent 4 }}
type: Opaque
stringData:
  MQTT_USER: {{ .Values.mqtt.username | quote }}
  MQTT_PASSWORD: {{ .Values.mqtt.password | quote }}
{{- end }}
