image:
  repository: eclipse-mosquitto
  tag: "2.0.18"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1883
  websocketPort: 9001

persistence:
  enabled: true
  size: 1Gi
  storageClass: vsphere-csi

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
