{{- if and .Values.mqtt.createSecret (not .Values.mqtt.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-mqtt-bridge.fullname" . }}-mqtt
  labels:
    {{- include "alertmanager-mqtt-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  MQTT_USER: {{ .Values.mqtt.user | quote }}
  MQTT_PASSWORD: {{ .Values.mqtt.password | quote }}
{{- end }}
