apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager-mqtt-bridge.fullname" . }}
  labels:
    {{- include "alertmanager-mqtt-bridge.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "alertmanager-mqtt-bridge.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
