apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unifi-network-application.fullname" . }}
  labels:
    {{- include "unifi-network-application.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "unifi-network-application.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "unifi-network-application.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: unifi-network-application
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
            - name: controller
              containerPort: 8080
              protocol: TCP
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: discovery
              containerPort: 10001
              protocol: UDP
          env:
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            - name: RUNAS_UID0
              value: {{ .Values.env.RUNAS_UID0 | quote }}
            - name: UNIFI_UID
              value: {{ .Values.env.UNIFI_UID | quote }}
            - name: UNIFI_GID
              value: {{ .Values.env.UNIFI_GID | quote }}
            - name: JVM_MAX_HEAP_SIZE
              value: {{ .Values.env.JVM_MAX_HEAP_SIZE | quote }}
          volumeMounts:
            - name: data
              mountPath: /unifi
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /status
              port: 8443
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /status
              port: 8443
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "unifi-network-application.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
