{{- if and .Values.vnc.create .Values.vnc.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vnc.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.vnc.password | quote }}
{{- end }}