{{- if .Values.vnc.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vnc.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: "changeme"
{{- end }}