---
apiVersion: v1
kind: Service
metadata:
  name: deconz
  labels:
    app.kubernetes.io/name: deconz
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: deconz
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
{{- end }}