{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: castlist-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
