{{- if .Values.registry.create }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"ghcr.io":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.registry.username .Values.registry.password (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
{{- end }}
