apiVersion: v1
kind: Secret
metadata:
  name: castlist-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
  CHROMECAST_IP: {{ .Values.secrets.chromecastIp | quote }}
