apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-ui.fullname" . }}-frontend
  labels:
    app: {{ include "k8s-ui.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8s-ui.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "k8s-ui.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
