apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ui-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-ui-frontend
  template:
    metadata:
      labels:
        app: k8s-ui-frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
