---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ui.fullname" . }}-frontend
  labels:
    app: {{ include "k8s-ui.name" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "k8s-ui.name" . }}-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ui-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: k8s-ui-backend
spec:
  type: ClusterIP
  selector:
    app: k8s-ui-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
