---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ui-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: k8s-ui-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ui-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: k8s-ui-backend
spec:
  type: ClusterIP
  selector:
    app: k8s-ui-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
