apiVersion: v1
kind: Service
metadata:
  name: k8s-ui-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: k8s-ui-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
