image:
  repository: deconzcommunity/deconz
  tag: 2.29.2

env:
  VNC_MODE: "1"
  VNC_PORT: "5900"
  WEB_PORT: "80"
  WS_PORT: "443"
  VERBOSE: "1"
  TZ: "Europe/Stockholm"

serviceAccountName: deconz

securityContext:
  privileged: true

vnc:
  create: true
  secretName: deconz-vnc-password
  password: changeme

## nodeSelector is used to select the node where the pod will be scheduled, label the node that has the USB device
## with the label "usb=zigbee" or change the value to match your node label
nodeSelector:
  usb: zigbee

pvc:
  name: deconz-config
  storageClassName: vsphere-csi
  size: 2560Mi


conbee:
  devicePath: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01H1HD-if00-port0

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: websocket
      port: 443
      targetPort: websocket
    - name: vnc
      port: 5900
      targetPort: vnc

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: deconz.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - deconz.example.com
      secretName: deconz-tls


gateway:
  enabled: false
  name: internal-shared
  namespace: cilium
  hostname: deconz.domain.com