{{- if .Values.ciliumGateway.enabled }}
{{- if .Values.ciliumGateway.gatewayName }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "home-assistant.fullname" . }}-external
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ciliumGateway.external.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.ciliumGateway.gatewayName }}
      namespace: {{ .Values.ciliumGateway.gatewayNamespace }}
  hostnames:
    - {{ .Values.ciliumGateway.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "home-assistant.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}

{{- if .Values.ciliumGateway.internalGatewayName }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "home-assistant.fullname" . }}-internal
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- toYaml .Values.ciliumGateway.internal.annotations | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.ciliumGateway.internalGatewayName }}
      namespace: {{ .Values.ciliumGateway.internalGatewayNamespace }}
  hostnames:
    - {{ .Values.ciliumGateway.internalHostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "home-assistant.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
{{- end }}
{{- range $name, $addon := .Values.addons }}
{{- if and $addon.enabled $addon.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "home-assistant.fullname" $ }}-{{ $name }}
spec:
  parentRefs:
    - name: {{ $addon.httpRoute.gateway }}
      namespace: {{ $addon.httpRoute.gatewayNamespace }}
  hostnames:
    - {{ $addon.httpRoute.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "home-assistant.fullname" $ }}-{{ $name }}
          port: {{ $addon.service.port }}
{{- end }}
{{- end }}