{{- if .Values.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config-root
  labels:
    app.kubernetes.io/name: home-assistant
    app: home-assistant
  annotations:
    velero.io/csi-volumesnapshot-class: "csi-vsphere-vsc"
spec:
  storageClassName: {{ .Values.persistence.config.storageClass }}
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}