---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8123
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}

{{- range $name, $addon := .Values.addons }}
{{- if and $addon.enabled $addon.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" $ }}-{{ $name }}
  labels:
    {{- include "home-assistant.labels" $ | nindent 4 }}
    addon: {{ $name }}
spec:
  type: {{ $addon.service.type }}
  ports:
    - port: {{ $addon.service.port }}
      targetPort: {{ $addon.service.port }}
      protocol: TCP
  selector:
    {{- include "home-assistant.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
