image:
  repo: ghcr.io/home-assistant/home-assistant
  tag: "2024.5"
  pullPolicy: IfNotPresent

env:
  TZ: "Europe/Stockholm"

hostNetwork: true

usb:
  enabled: false
  devices:
    - /dev/ttyACM0
    - /dev/ttyUSB0

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: home.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

ciliumGateway:
  enabled: false
  gatewayName: cilium-external
  gatewayNamespace: kube-system
  hostname: home.example.com
  external:
    annotations: {}
  internalGatewayName: cilium-internal
  internalGatewayNamespace: kube-system
  internalHostname: home.internal.local
  internal:
    annotations: {}

service:
  type: ClusterIP
  port: 8123
  nodePort: 30812

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

metrics:
  enabled: false
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    labels:
      release: prometheus

nodeSelector: {}
tolerations: []
affinity: {}

addons:
  codeserver:
    enabled: true
    container:
      name: codeserver
      image: codercom/code-server:4.7.1
      imagePullPolicy: IfNotPresent
      workingDir: "/config"
      args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        - --port
        - "12321"
        - /config
      ports:
        - containerPort: 12321
      volumeMounts:
        - name: config
          mountPath: /config
      env:
        - name: TZ
          value: "Europe/Stockholm"
        - name: HOME
          value: /config
      securityContext:
        runAsUser: 0
      resources: {}
    service:
      type: ClusterIP
      port: 12321
    httpRoute:
      enabled: false
      hostname: vshass.domain.com
      gateway: internal-shared
      gatewayNamespace: kube-system
    ingress:
      enabled: false
      ingressClassName: nginx-example
      annotations:
        kubernetes.io/ingress.class: "haproxy"
      rules:
        - host: hass.domain.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: test
                    port:
                      number: 12321
      tls: []
