{{- if .Values.gatewayapi.enabled }}
{{- $name := printf "gateway-api-crds-%s-%s" (replace .Values.gatewayapi.version "." "-") .Values.gatewayapi.channel | trunc 63 }}
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
  strategy: {{ .Values.gatewayapi.applyStrategy }}
  resources:
    - kind: ConfigMap
      name: {{ $name }}
{{- end }}
