{{- range .Values.machineTemplates }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: {{ $.Values.cluster.name }}-{{ .name }}
  namespace: {{ $.Values.cluster.name }}
spec:
  template:
    spec:
      cloneMode: {{ .cloneMode }}
      datacenter: {{ $.Values.vsphere.datacenter }}
      datastore: {{ .vcenterDatastore }}
      diskGiB: {{ .diskSize }}
      folder: "{{ .vcenterFolder }}"
      memoryMiB: {{ .memory }}
      network:
        devices:
        - addressesFromPools:
          - apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: {{ $.Values.cluster.name }}-ip-pool
          nameservers:
          - {{ $.Values.network.nameserver }}
          networkName: {{ .network }}
      numCPUs: {{ .cpu }}
      os: Linux
      powerOffMode: trySoft
      resourcePool: {{ .resourcePool }}
      server: {{ $.Values.vsphere.serverIP }}
      storagePolicyName: "{{ .storagePolicyName }}"
      template: {{ .isoTemplate }}
      thumbprint: {{ $.Values.vsphere.thumbprint }}
{{- end }}