image:
  repository: ghcr.io/your-org/my-react-site
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []  # Example: [name: regcred]

securityContext:
  enabled: true
  fsGroup: 2000
  runAsUser: 1000
  runAsGroup: 3000
  runAsNonRoot: true

containerSecurityContext:
  enabled: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: null

service:
  port: 80
  targetPort: 80

serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 30s
  path: /metrics
  port: http
  labels:
    release: prometheus-stack

ingress:
  enabled: false
  className: "nginx"
  host: "my-site.local"
  path: "/"
  tls: false

gateway:
  enabled: true
  name: "my-gateway"
  namespace: "gateway-namespace"
  host: "my-site.local"
