apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ghost.fullname" . }}
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ghost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ghost.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ghost
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 2368
              protocol: TCP
          env:
            - name: url
              value: {{ .Values.settings.url | quote }}
            - name: logging__transports
              value: '["stdout"]'
            - name: NODE_ENV
              value: production
            - name: database__client
              value: {{ .Values.database.client | quote }}
            - name: database__connection__host
              value: {{ .Values.database.host | quote }}
            - name: database__connection__port
              value: {{ .Values.database.port | quote }}
            - name: database__connection__database
              value: {{ .Values.database.name | quote }}
            - name: database__connection__user
              value: {{ .Values.database.user | quote }}
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.passwordSecret.name }}
                  key: {{ .Values.database.passwordSecret.key }}
            {{- if .Values.mail.enabled }}
            - name: mail__transport
              value: {{ .Values.mail.transport | quote }}
            - name: mail__from
              value: {{ .Values.mail.from | quote }}
            - name: mail__options__host
              value: {{ .Values.mail.host | quote }}
            - name: mail__options__port
              value: {{ .Values.mail.port | quote }}
            - name: mail__options__secure
              value: {{ .Values.mail.secure | quote }}
            - name: mail__options__auth__user
              value: {{ .Values.mail.user | quote }}
            - name: mail__options__auth__pass
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mail.passwordSecret.name }}
                  key: {{ .Values.mail.passwordSecret.key }}
            {{- end }}
          startupProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: "localhost:2368"
                {{- if hasPrefix "https" .Values.settings.url }}
                - name: x-forwarded-proto
                  value: https
                {{- end }}
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: "localhost:2368"
                {{- if hasPrefix "https" .Values.settings.url }}
                - name: x-forwarded-proto
                  value: https
                {{- end }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: "localhost:2368"
                {{- if hasPrefix "https" .Values.settings.url }}
                - name: x-forwarded-proto
                  value: https
                {{- end }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: content
              mountPath: /var/lib/ghost/content
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        - name: content
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "ghost.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
