apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worklog.api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worklog.labels" . | nindent 4 }}
    {{- include "worklog.api.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "worklog.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worklog.api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repo }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.secretName }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
