apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worklog.frontend.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worklog.labels" . | nindent 4 }}
    {{- include "worklog.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "worklog.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worklog.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repo }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
