name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: read

jobs:
  changes:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    if: github.repository == 'janip81/helm-charts'
    outputs:
      charts: ${{ steps.filter.outputs.charts }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Artifact Hub lint
        run: |
          wget -nv https://github.com/artifacthub/hub/releases/download/v1.20.0/ah_1.20.0_linux_amd64.tar.gz
          echo '9027626f19ff9f3ac668f222917130ac885e289e922e1428bfd2e7f066324e31 *ah_1.20.0_linux_amd64.tar.gz' | shasum -c
          tar -xzvf ah_1.20.0_linux_amd64.tar.gz ah
          ./ah lint
          rm -f ./ah ./ah_1.20.0_linux_amd64.tar.gz

      - name: Detect chart changes
        uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'charts/*/Chart.yaml'
              - 'charts/*/values.yaml'
              - 'charts/*/templates/**'

  lint-test:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.charts == 'true' && github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        run: ct list-changed --target-branch main

      - name: Run chart-testing (lint)
        run: ct lint --target-branch main 2>&1
      
      - name: Determine if capi-cluster chart was changed
        id: changed
        run: |
          echo "capi_changed=false" >> $GITHUB_OUTPUT
          ct list-changed --target-branch main > changed.txt
          cat changed.txt
          if grep -q 'charts/capi-cluster' changed.txt; then
            echo "capi_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create kind cluster
        if: steps.changed.outputs.capi_changed != 'true'
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        if: steps.changed.outputs.capi_changed != 'true'
        run: ct install --config ./ct-install-skip.yaml 2>&1

  release:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: |
      github.ref == 'refs/heads/main' &&
      github.repository == 'janip81/helm-charts' &&
      needs.changes.outputs.charts == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.CR_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.CR_TOKEN }}
          CR_SKIP_EXISTING: "true"
          CR_GENERATE_RELEASE_NOTES: "true"
