{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "my-react-site.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - {{ .Values.gateway.host }}
  rules:
    - backendRefs:
        - name: {{ include "my-react-site.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
