{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "gameledger.fullname" . }}
  labels: {{- include "gameledger.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.gateway.annotations }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  parentRefs:
    {{- toYaml .Values.gateway.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.gateway.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "gameledger.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
