{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gameledger.fullname" . }}-migrate
  labels: {{- include "gameledger.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels: {{- include "gameledger.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "gameledger.fullname" . }}-secret
            - configMapRef:
                name: {{ include "gameledger.fullname" . }}-config
          command: ["/bin/sh","-lc"]
          args:
            - |
              echo "Running prisma migrate deploy…"
              prisma migrate deploy
{{- end }}
